development:
  adapter: mysql2
  database: tender_scraper_dev
  username: scraper_dev
  password: scraper_dev
  host: 127.0.0.1

test:
  adapter: mysql2
  database: tender_scraper_test
  username: scraper_test
  password: scraper_test
  host: 127.0.0.1
